/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package edu.lmu.cs.xlg.manatee.syntax;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int BR = 40;
  /** RegularExpression Id. */
  int NUMLIT = 41;
  /** RegularExpression Id. */
  int EXPONENT = 42;
  /** RegularExpression Id. */
  int CHARLIT = 43;
  /** RegularExpression Id. */
  int STRLIT = 44;
  /** RegularExpression Id. */
  int ID = 45;
  /** RegularExpression Id. */
  int BOOL = 46;
  /** RegularExpression Id. */
  int LETTER = 47;
  /** RegularExpression Id. */
  int DIGIT = 48;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "<token of kind 3>",
    "\"I\"",
    "\"EI\"",
    "\"E\"",
    "\"DF\"",
    "\"DC\"",
    "\"L\"",
    "\"R\"",
    "\"B\"",
    "\"N\"",
    "\"S\"",
    "\"C\"",
    "\"Y\"",
    "\"< >\"",
    "\"T\"",
    "\"F\"",
    "\"P\"",
    "\"LU\"",
    "\"LF\"",
    "\"LW\"",
    "\":\"",
    "\",\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"==\"",
    "\"^\"",
    "\"<\"",
    "\"<=\"",
    "\"=\"",
    "\">=\"",
    "\">\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "<BR>",
    "<NUMLIT>",
    "<EXPONENT>",
    "<CHARLIT>",
    "<STRLIT>",
    "<ID>",
    "<BOOL>",
    "<LETTER>",
    "<DIGIT>",
    "\"P \"",
    "\"_\"",
    "\"|\"",
    "\"||\"",
    "\"&&\"",
    "\"!=\"",
    "\"%\"",
    "\"**\"",
    "\"!\"",
    "\"~\"",
  };

}
